"""Custom exceptions."""


class ValidationError(ValueError):
    """Data is invalid."""

    pass
